/* ==========================================================================
   INAI REPUBLIC - Blog Metadata (js/blog-data.js)
   Generated by %TEMP%\blog-build.js from verified WordPress source content.
   Metadata only: article bodies are inlined statically in blog/*.html.
   ========================================================================== */
window.INAI_BLOG = {
  posts: [
    {
      "id": 1,
      "slug": "jangan-putus-asa",
      "title": "Jangan Putus Asa",
      "date": "2026-08-21",
      "excerpt": "Jangan putus asa daripada rahmat Allah SWT. Ketahui bagaimana Islam mengajar kita untuk bersabar, bersangka baik dan terus berusaha di jalan-Nya.",
      "summary": "Jangan putus asa daripada rahmat Allah SWT. Ketahui bagaimana Islam mengajar kita untuk bersabar, bersangka baik dan terus berusaha di…",
      "image": "https://inairepublic.com/wp-content/uploads/2026/08/ChatGPT-Image-Aug-21-2026-12_06_00-PM.png",
      "url": "blog/jangan-putus-asa.html",
      "readingMinutes": 4,
      "source": "https://inairepublic.com/jangan-putus-asa/"
    },
    {
      "id": 2,
      "slug": "hijrah-diri",
      "title": "Hijrah Diri",
      "date": "2026-07-29",
      "excerpt": "Hijrah bukan sekadar perubahan luaran, tetapi perjalanan hati menuju iman, akhlak dan reda Allah SWT. Artikel ini menghuraikan makna hijrah sebenar berdasarkan al-Quran, hadis dan sirah Rasulullah SAW.",
      "summary": "Hijrah bukan sekadar perubahan luaran, tetapi perjalanan hati menuju iman, akhlak dan reda Allah SWT. Artikel ini menghuraikan makna hijrah…",
      "image": "https://inairepublic.com/wp-content/uploads/2026/07/ChatGPT-Image-Jul-29-2026-10_20_08-AM.png",
      "url": "blog/hijrah-diri.html",
      "readingMinutes": 4,
      "source": "https://inairepublic.com/hijrah-diri/"
    },
    {
      "id": 3,
      "slug": "kecantikan-menurut-islam",
      "title": "Kecantikkan Ciptaan Dan Tuturkata",
      "date": "2026-07-29",
      "excerpt": "Artikel ini membincangkan konsep kecantikan dan keindahan menurut Islam berdasarkan al-Quran dan hadis, peranan bahasa yang indah dalam dakwah, serta bagaimana alam ciptaan Allah menjadi tanda kebesaran-Nya untuk manusia berfikir dan kembali kepada fitrah.",
      "summary": "Artikel ini membincangkan konsep kecantikan dan keindahan menurut Islam berdasarkan al-Quran dan hadis, peranan bahasa yang indah dalam…",
      "image": "https://inairepublic.com/wp-content/uploads/2026/07/ChatGPT-Image-Jul-29-2026-10_08_18-AM.png",
      "url": "blog/kecantikan-menurut-islam.html",
      "readingMinutes": 5,
      "source": "https://inairepublic.com/kecantikan-menurut-islam/"
    },
    {
      "id": 4,
      "slug": "kecantikan-adalah-ibadah",
      "title": "Kecantikan Adalah Ibadah",
      "date": "2026-07-22",
      "excerpt": "Kecantikan dalam Islam bukan sekadar rupa paras, tetapi sebahagian daripada ibadah apabila menjaga kebersihan, penampilan dan akhlak dilakukan kerana Allah SWT. Ketahui panduan syarak mengenai kecantikan zahir dan batin.",
      "summary": "Kecantikan dalam Islam bukan sekadar rupa paras, tetapi sebahagian daripada ibadah apabila menjaga kebersihan, penampilan dan akhlak…",
      "image": "https://inairepublic.com/wp-content/uploads/2026/07/ChatGPT-Image-Jul-22-2026-09_34_14-AM.png",
      "url": "blog/kecantikan-adalah-ibadah.html",
      "readingMinutes": 2,
      "source": "https://inairepublic.com/kecantikan-adalah-ibadah/"
    },
    {
      "id": 5,
      "slug": "berhias-ketika-hari-raya-menurut-islam",
      "title": "Mencantikkan Diri Dan Berhias Ketika Berhari Raya Dalam Islam",
      "date": "2026-07-21",
      "excerpt": "Ketahui panduan berhias ketika hari raya menurut Islam berdasarkan al-Quran, hadis dan pandangan ulama termasuk adab berpakaian, wangian dan mewarnakan uban.",
      "summary": "Ketahui panduan berhias ketika hari raya menurut Islam berdasarkan al-Quran, hadis dan pandangan ulama termasuk adab berpakaian, wangian…",
      "image": "https://inairepublic.com/wp-content/uploads/2026/07/ChatGPT-Image-Jul-21-2026-10_31_09-AM.png",
      "url": "blog/berhias-ketika-hari-raya-menurut-islam.html",
      "readingMinutes": 3,
      "source": "https://inairepublic.com/berhias-ketika-hari-raya-menurut-islam/"
    },
    {
      "id": 6,
      "slug": "konsep-kecantikan-dalam-islam",
      "title": "Konsep Kecantikan Dalam Islam",
      "date": "2026-07-17",
      "excerpt": "Islam menggalakkan kecantikan yang sederhana dan berakhlak. Ketahui konsep kecantikan dalam Islam serta panduan berhias mengikut syariat.",
      "summary": "Islam menggalakkan kecantikan yang sederhana dan berakhlak. Ketahui konsep kecantikan dalam Islam serta panduan berhias mengikut syariat.",
      "image": "https://inairepublic.com/wp-content/uploads/2026/07/ChatGPT-Image-Jul-17-2026-10_29_00-AM.png",
      "url": "blog/konsep-kecantikan-dalam-islam.html",
      "readingMinutes": 3,
      "source": "https://inairepublic.com/konsep-kecantikan-dalam-islam/"
    },
    {
      "id": 7,
      "slug": "hukum-mewarnakan-rambut-dengan-warna-hitam",
      "title": "Hukum Mewarnakan Rambut Dengan Warna Hitam",
      "date": "2026-07-03",
      "excerpt": "Ketahui hukum mewarnakan rambut dengan warna hitam menurut Islam berdasarkan hadis dan pandangan ulama serta panduan memilih pewarna rambut halal dan telus air.",
      "summary": "Ketahui hukum mewarnakan rambut dengan warna hitam menurut Islam berdasarkan hadis dan pandangan ulama serta panduan memilih pewarna rambut…",
      "image": "https://inairepublic.com/wp-content/uploads/2026/07/man-receding-gray-hair-before-hair-transplant-left-fuller-darker-hairline-after-right-scaled.jpg",
      "url": "blog/hukum-mewarnakan-rambut-dengan-warna-hitam.html",
      "readingMinutes": 2,
      "source": "https://inairepublic.com/hukum-mewarnakan-rambut-dengan-warna-hitam/"
    },
    {
      "id": 8,
      "slug": "inai-republic-tak-halal-betul-ke",
      "title": "Inai Republic tak halal? Betul ke?",
      "date": "2023-11-08",
      "excerpt": "Di antara hak wanita itu adalah berhias dan memakai perhiasan. Islam tidak melarang untuk mereka bercantik-cantik dengan syarat-syarat tertentu. Ini kerana fitrah seorang wanita itu sukakan kecantikan dan kekemasan. Islam telah memberi ruang dan panduan bagi seorang wanita itu berhias. Firman Allah SWT: ‎قُلْ مَنْ حَرَّمَ زِينَةَ اللَّهِ الَّتِي أَخْرَجَ لِعِبَادِهِ وَالطَّيِّبَاتِ مِنَ الرِّزْقِ Maksudnya: […]",
      "summary": "Di antara hak wanita itu adalah berhias dan memakai perhiasan. Islam tidak melarang untuk mereka bercantik-cantik dengan syarat-syarat…",
      "image": "https://inairepublic.com/wp-content/uploads/2023/11/photo_2021-12-13-12.36.34-1024x576-1.jpeg",
      "url": "blog/inai-republic-tak-halal-betul-ke.html",
      "readingMinutes": 8,
      "source": "https://inairepublic.com/inai-republic-tak-halal-betul-ke/"
    }
  ]
};
